"""Provider selection and routing.

None of these make a network call. What they protect is the wiring around the
providers, which is where a mistake is silent: picking the wrong vendor, or
falling back to a default vendor after a typo, produces documents that look
completely normal and were generated by something nobody chose.
"""

import pytest

from app.llm import provider as llm
from app.llm.provider import (
    GeminiProvider,
    LLMNotConfiguredError,
    OpenAIProvider,
    RoutedProvider,
    get_llm_provider,
    llm_configured,
)


@pytest.fixture
def configure(monkeypatch):
    """Set provider/key settings for one test."""

    def _apply(**kw):
        defaults = {
            "llm_provider": "anthropic", "llm_compile_provider": None,
            "anthropic_api_key": None, "gemini_api_key": None, "openai_api_key": None,
        }
        for key, value in {**defaults, **kw}.items():
            monkeypatch.setattr(llm.settings, key, value)

    return _apply


# ------------------------------------------------------------------ selection
def test_the_selected_provider_is_the_one_built(configure):
    configure(llm_provider="gemini", gemini_api_key="k")
    assert isinstance(get_llm_provider(allow_unscoped=True), GeminiProvider)

    configure(llm_provider="anthropic", anthropic_api_key="k")
    assert isinstance(get_llm_provider(allow_unscoped=True), llm.AnthropicProvider)

    configure(llm_provider="openai", openai_api_key="k")
    assert isinstance(get_llm_provider(allow_unscoped=True), OpenAIProvider)


def test_a_key_for_the_other_vendor_does_not_count(configure):
    """Holding an Anthropic key while LLM_PROVIDER=gemini is not a configured
    install -- it is a misconfigured one, and must say so."""
    configure(llm_provider="gemini", anthropic_api_key="anthropic-key")
    assert llm_configured() is False
    with pytest.raises(LLMNotConfiguredError, match="GEMINI_API_KEY"):
        get_llm_provider("Chat", allow_unscoped=True)


def test_an_unknown_provider_name_is_rejected_not_defaulted(configure):
    """A typo in LLM_PROVIDER must not quietly route every document through
    whichever vendor happens to be the default."""
    configure(llm_provider="gemni", gemini_api_key="k", anthropic_api_key="k")
    assert llm_configured() is False
    with pytest.raises(LLMNotConfiguredError, match="not a known provider"):
        get_llm_provider(allow_unscoped=True)


@pytest.mark.parametrize("raw", ["  GEMINI  ", "Gemini", "gemini"])
def test_provider_name_is_case_and_space_insensitive(configure, raw):
    configure(llm_provider=raw, gemini_api_key="k")
    assert isinstance(get_llm_provider(allow_unscoped=True), GeminiProvider)


# -------------------------------------------------------------------- routing
def test_compile_and_generate_can_use_different_vendors(configure):
    configure(llm_provider="gemini", llm_compile_provider="anthropic",
              gemini_api_key="k", anthropic_api_key="k")
    provider = get_llm_provider(allow_unscoped=True)
    assert isinstance(provider, RoutedProvider)
    assert llm_configured("generate") is True
    assert llm_configured("compile") is True


def test_routing_sends_each_purpose_to_its_own_vendor():
    class Fake(llm.LLMProvider):
        def __init__(self, tag):
            self.tag = tag
            self.calls = []

        def generate(self, **kw):
            self.calls.append("generate")
            return llm.LLMResult(text=self.tag, blocks=[], input_tokens=0, output_tokens=0, model=self.tag)

        def structured(self, *, system, prompt, schema, purpose="generate"):
            self.calls.append(f"structured:{purpose}")
            return llm.StructuredResult(data={"who": self.tag}, model=self.tag)

    gen, comp = Fake("generator"), Fake("compiler")
    routed = RoutedProvider(gen, comp)

    assert routed.structured(system="", prompt="", schema={}, purpose="compile").data == {"who": "compiler"}
    assert routed.structured(system="", prompt="", schema={}, purpose="generate").data == {"who": "generator"}
    # Narrative prose is per-document work, so it follows the generate vendor.
    assert routed.generate(instructions="", context_chunks=[], fact_sheet={}).model == "generator"
    assert comp.calls == ["structured:compile"]
    assert gen.calls == ["structured:generate", "generate"]


def test_a_routed_setup_still_fails_if_only_one_vendor_has_a_key(configure):
    configure(llm_provider="gemini", llm_compile_provider="anthropic", gemini_api_key="k")
    assert llm_configured("generate") is True
    assert llm_configured("compile") is False
    with pytest.raises(LLMNotConfiguredError, match="ANTHROPIC_API_KEY"):
        get_llm_provider(allow_unscoped=True)


# ------------------------------------------------- Gemini response handling
class _Resp:
    """Shapes the SDK actually returns, reduced to what _read inspects."""

    def __init__(self, *, finish=None, text=None, block_reason=None, candidates=True):
        self.prompt_feedback = type("PF", (), {"block_reason": block_reason})()
        self.text = text
        if candidates:
            reason = type("R", (), {"name": finish})() if finish else None
            self.candidates = [type("C", (), {"finish_reason": reason})()]
        else:
            self.candidates = []


@pytest.mark.parametrize("finish", ["SAFETY", "PROHIBITED_CONTENT", "BLOCKLIST", "SPII", "RECITATION"])
def test_safety_finishes_are_refusals_not_crashes(finish):
    text, error = GeminiProvider._read(_Resp(finish=finish, text="partial"))
    assert text is None and "declined" in error


def test_a_blocked_prompt_is_reported_rather_than_raising():
    """With a blocked prompt there are no candidates at all, so reading
    `.text` would raise several layers away from the cause."""
    text, error = GeminiProvider._read(_Resp(block_reason="SAFETY", candidates=False))
    assert text is None and "blocked" in error


def test_truncated_output_is_never_parsed_as_json():
    """Gemini bills thinking against the output budget and spends it freely, so
    hitting the ceiling is reachable -- and half a JSON manifest is worse than
    none."""
    text, error = GeminiProvider._read(_Resp(finish="MAX_TOKENS", text='{"fields": [{"id"'))
    assert text is None and "truncated" in error


def test_a_clean_response_passes_through():
    text, error = GeminiProvider._read(_Resp(finish="STOP", text='{"ok": true}'))
    assert error is None and text == '{"ok": true}'


def test_thinking_tokens_are_billed_as_output():
    """Otherwise the analytics page under-reports Gemini cost against Anthropic
    by whatever the model spent thinking -- which testing showed can exceed the
    visible answer several times over."""
    usage = type("U", (), {"prompt_token_count": 100, "candidates_token_count": 40, "thoughts_token_count": 900})()
    assert GeminiProvider._usage(type("R", (), {"usage_metadata": usage})()) == (100, 940)


def test_missing_usage_metadata_does_not_break_accounting():
    assert GeminiProvider._usage(type("R", (), {"usage_metadata": None})()) == (0, 0)


# ------------------------------------------------- OpenAI response handling
class _OAResp:
    """Shapes the Responses API actually returns, reduced to what _read reads."""

    def __init__(self, *, status="completed", output_text=None, refusal=None,
                 incomplete_reason=None, usage=None):
        self.status = status
        self.output_text = output_text
        self.incomplete_details = type("D", (), {"reason": incomplete_reason})()
        self.usage = usage
        if refusal is not None:
            part = type("P", (), {"type": "refusal", "refusal": refusal})()
            self.output = [type("I", (), {"content": [part]})()]
        else:
            part = type("P", (), {"type": "output_text", "text": output_text})()
            self.output = [type("I", (), {"content": [part]})()]


def test_an_openai_refusal_is_reported_not_parsed_as_empty():
    """A refusal still carries status == "completed" and an empty output_text,
    so checking status first would lose the reason entirely."""
    text, error = OpenAIProvider._read(_OAResp(refusal="I can't help with that."))
    assert text is None and "declined" in error and "I can't help with that." in error


def test_openai_truncated_output_is_never_parsed_as_json():
    """Reasoning is billed against max_output_tokens and spent before any
    visible text, so a large compile can hit the ceiling mid-manifest."""
    text, error = OpenAIProvider._read(
        _OAResp(status="incomplete", incomplete_reason="max_output_tokens", output_text='{"fields": [{"id"')
    )
    assert text is None and "truncated" in error


def test_openai_other_incomplete_reasons_are_reported():
    text, error = OpenAIProvider._read(_OAResp(status="incomplete", incomplete_reason="content_filter"))
    assert text is None and "incomplete" in error and "content_filter" in error


def test_an_empty_openai_response_is_an_error_not_an_empty_document():
    text, error = OpenAIProvider._read(_OAResp(output_text=""))
    assert text is None and "empty" in error


def test_a_clean_openai_response_passes_through():
    text, error = OpenAIProvider._read(_OAResp(output_text='{"ok": true}'))
    assert error is None and text == '{"ok": true}'


def test_openai_reasoning_tokens_are_already_billed_as_output():
    """Unlike Gemini, output_tokens already includes reasoning, so folding it
    in again here would double-count it on the analytics page."""
    usage = type("U", (), {"input_tokens": 100, "output_tokens": 940})()
    assert OpenAIProvider._usage(_OAResp(output_text="x", usage=usage)) == (100, 940)


def test_missing_openai_usage_does_not_break_accounting():
    assert OpenAIProvider._usage(_OAResp(output_text="x", usage=None)) == (0, 0)


def test_openai_can_compile_while_another_vendor_generates(configure):
    """The whole point of LLM_COMPILE_PROVIDER: compile once on the strong
    model, generate per document on the cheap one, across vendors."""
    configure(llm_provider="openai", llm_compile_provider="anthropic",
              openai_api_key="k", anthropic_api_key="k")
    provider = get_llm_provider(allow_unscoped=True)
    assert isinstance(provider, RoutedProvider)
    assert llm_configured("generate") is True and llm_configured("compile") is True


def test_an_openai_key_does_not_satisfy_a_different_selected_vendor(configure):
    configure(llm_provider="gemini", openai_api_key="openai-key")
    assert llm_configured() is False
    with pytest.raises(LLMNotConfiguredError, match="GEMINI_API_KEY"):
        get_llm_provider("Chat", allow_unscoped=True)
