"""What a delivered document says about how it was made: nothing.

Every test here produces a real output through the product's own code -- emit,
the HTML assembly, the fill engine, the PDF converter, the spreadsheet builder,
the download endpoints -- and then opens the package and reads what a recipient
could read: the core and extended properties, the parts in the archive, the
settings, the PDF information dictionary, the file name and the zip headers.

The things that must not be there: the generator library, the converter and its
build, the server's time zone, the product's name, internal ids and project
names, drafting labels and retrieval citation markers.
"""

from __future__ import annotations

import io
import os
import re
import zipfile
from datetime import datetime

import docx
import pytest
from sqlalchemy import select

from app.db import SessionLocal
from app.generation.filenames import (
    content_disposition,
    document_filename,
    safe_filename,
    unique_name,
)
from app.generation.reproducibility import (
    FIXED_ZIP_TIMESTAMP,
    fixed_zip_entry,
    normalisation_failures,
    normalise_core_properties,
    normalise_docx,
)
from app.templates import base_docx

TOOLCHAIN = ("python-docx", "openpyxl", "Openpyxl", "LibreOffice", "DocuMind",
             "Microsoft Macintosh Word", "Normal.dotm", "generated by")


def _auth(token):
    return {"Authorization": f"Bearer {token}"}


def _parts(path) -> dict:
    with zipfile.ZipFile(path if isinstance(path, io.BytesIO) else str(path)) as archive:
        return {name: archive.read(name) for name in archive.namelist()}


def _assert_neutral_package(path):
    parts = _parts(path)
    names = set(parts)
    assert not any(n.startswith("customXml/") for n in names), sorted(names)
    assert "docProps/thumbnail.jpeg" not in names
    core = parts["docProps/core.xml"].decode()
    app = parts.get("docProps/app.xml", b"").decode()
    for word in TOOLCHAIN:
        assert word not in core and word not in app, word
    assert "<Application>" not in app and "<Template>" not in app
    settings = parts["word/settings.xml"].decode()
    assert "w:rsids" not in settings and "w14:docId" not in settings
    assert b"thumbnail" not in parts["_rels/.rels"]
    assert b"customXml" not in parts["[Content_Types].xml"]
    assert normalisation_failures(str(path)) == []
    return parts


# ------------------------------------------------------------ the base package

def test_the_checked_in_base_is_what_the_recipe_builds(tmp_path):
    rebuilt = base_docx.build(str(tmp_path / "base.docx"))
    with open(rebuilt, "rb") as a, open(base_docx.BASE_DOCX, "rb") as b:
        assert a.read() == b.read(), "regenerate with python -m app.templates.base_docx"


def test_the_base_keeps_the_default_styles_byte_for_byte():
    default = _parts(base_docx._default_template())
    base = _parts(base_docx.BASE_DOCX)
    for part in ("word/styles.xml", "word/numbering.xml", "word/theme/theme1.xml",
                 "word/fontTable.xml", "word/document.xml", "word/stylesWithEffects.xml"):
        assert base[part] == default[part], part


def test_a_changed_default_template_fails_the_build_loudly(tmp_path):
    source = tmp_path / "odd.docx"
    with zipfile.ZipFile(base_docx._default_template()) as src, \
            zipfile.ZipFile(source, "w") as out:
        for info in src.infolist():
            if info.filename != "docProps/thumbnail.jpeg":
                out.writestr(info, src.read(info.filename))
    with pytest.raises(base_docx.BaseTemplateChanged):
        base_docx.build(str(tmp_path / "x.docx"), str(source))

    reshaped = tmp_path / "reshaped.docx"
    with zipfile.ZipFile(base_docx._default_template()) as src, \
            zipfile.ZipFile(reshaped, "w") as out:
        for info in src.infolist():
            data = src.read(info.filename)
            if info.filename == "word/settings.xml":
                data = data.replace(b"<w:savePreviewPicture/>", b"")
            out.writestr(info, data)
    with pytest.raises(base_docx.BaseTemplateChanged):
        base_docx.build(str(tmp_path / "y.docx"), str(reshaped))


def test_new_document_opens_the_neutral_base(tmp_path):
    document = base_docx.new_document()
    document.add_paragraph("Hello")
    out = tmp_path / "n.docx"
    document.save(str(out))
    normalise_docx(str(out))
    _assert_neutral_package(out)


# ------------------------------------------------------ from-scratch writers

def _body():
    from app.templates import blueprint as bp

    return bp.normalise_body({"blocks": [
        {"kind": "paragraph", "style": "Heading1",
         "segments": [{"role": "static", "text": "Quarterly summary"}]},
        {"kind": "paragraph",
         "segments": [{"role": "static", "text": "Nothing to report."}]},
    ], "sect_pr_from": None})


def test_an_emitted_document_names_no_toolchain_and_is_reproducible(tmp_path):
    from app.templates.emit_docx import emit

    first, second = tmp_path / "a.docx", tmp_path / "b.docx"
    emit(_body(), str(first))
    emit(_body(), str(second))
    parts = _assert_neutral_package(first)
    assert first.read_bytes() == second.read_bytes()
    # The layout comes from exactly the styles, numbering and theme a document
    # on python-docx's own package would have had.
    before = tmp_path / "default.docx"
    docx.Document().save(str(before))
    default = _parts(before)
    for part in ("word/styles.xml", "word/numbering.xml", "word/theme/theme1.xml"):
        assert parts[part] == default[part], part


def test_an_html_assembled_document_names_no_toolchain_and_is_reproducible(tmp_path):
    from app.generation.legacy_assembly import assemble_from_html

    html = "<h1>Offer</h1><p>Dear <b>Ana</b>,</p><ul><li>One</li></ul>"
    first, second = tmp_path / "a.docx", tmp_path / "b.docx"
    assemble_from_html(html, str(first))
    assemble_from_html(html, str(second))
    _assert_neutral_package(first)
    assert first.read_bytes() == second.read_bytes()
    assert "Offer" in "\n".join(p.text for p in docx.Document(str(first)).paragraphs)


# --------------------------------------------- F8: the template's own bookkeeping

CORE = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    b'<cp:coreProperties '
    b'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
    b'xmlns:dc="http://purl.org/dc/elements/1.1/" '
    b'xmlns:dcterms="http://purl.org/dc/terms/">'
    b"<dc:title>Offer of employment</dc:title><dc:subject>Master: HR offer ANZ</dc:subject>"
    b"<dc:creator>Priya Sharma</dc:creator><cp:keywords>HR-TPL-ANZ-014</cp:keywords>"
    b"<dc:description>Owner: Talent Ops. Approvers: J. Lee</dc:description>"
    b"<cp:lastModifiedBy>j.lee</cp:lastModifiedBy><cp:revision>14</cp:revision>"
    b"<cp:category>Templates</cp:category><cp:contentStatus>Approved</cp:contentStatus>"
    b"<dcterms:created>2026-07-03T11:07:00Z</dcterms:created>"
    b"</cp:coreProperties>"
)


def test_outbound_core_properties_drop_the_templates_bookkeeping():
    cleaned = normalise_core_properties(CORE).decode()
    for gone in ("HR-TPL-ANZ-014", "Talent Ops", "j.lee", "Master: HR", "Templates",
                 "Approved", ">14<"):
        assert gone not in cleaned, gone
    assert "<cp:revision>1</cp:revision>" in cleaned
    assert "Offer of employment" in cleaned and "Priya Sharma" in cleaned
    assert normalise_core_properties(cleaned.encode()) == cleaned.encode()


def test_the_static_region_gate_forgives_the_scrub_and_nothing_more(tmp_path):
    from app.qa.layout_integrity import docprops_failures

    def package(name, core):
        path = tmp_path / name
        with zipfile.ZipFile(path, "w") as archive:
            archive.writestr("docProps/core.xml", core)
        return str(path)

    template = package("t.docx", CORE)
    scrubbed = package("o.docx", normalise_core_properties(CORE))
    assert docprops_failures(template, scrubbed) == []
    retitled = package("r.docx", normalise_core_properties(
        CORE.replace(b"Offer of employment", b"Something else")))
    assert docprops_failures(template, retitled)


def test_a_filled_letter_carries_no_template_bookkeeping_and_passes_its_gate(
        fixtures_dir, tmp_path):
    """The fill path edits the customer's own package; its core properties are
    scrubbed on the way out and the static-region gate still passes."""
    from app.compiler.rule_compiler import compile_manifest
    from app.generation.docx_renderer import fill_template
    from app.generation.source_ingestion import extract_records
    from app.generation.source_resolver import apply_binding, suggest_bindings
    from app.qa.layout_integrity import structural_failures
    from app.templates.parsers.docx_prescan import prescan

    original = fixtures_dir / "templates" / "hospira_offer.docx"
    if not original.exists():
        pytest.skip("client template master not present")
    # The master, with the bookkeeping a real one carries written into it.
    template = tmp_path / "template.docx"
    with zipfile.ZipFile(original) as src, zipfile.ZipFile(template, "w") as out:
        for info in src.infolist():
            data = src.read(info.filename)
            if info.filename == "docProps/core.xml":
                data = CORE
            out.writestr(info, data)

    compiled = compile_manifest(prescan(str(template)))
    manifest = {"fields": compiled.fields, "conditions": compiled.conditions,
                "blocks": compiled.blocks, "delete_always": compiled.delete_always}
    columns, records = extract_records(
        str(fixtures_dir / "records" / "colleagues.xlsx"), "xlsx")
    bindings = suggest_bindings(manifest, columns).as_field_bindings()
    out = tmp_path / "letter.docx"
    result = fill_template(str(template), str(out), manifest,
                           apply_binding(records[0], bindings), locale="en_AU")

    core = _parts(out)["docProps/core.xml"].decode()
    assert "HR-TPL-ANZ-014" not in core and "Talent Ops" not in core
    assert "<cp:revision>1</cp:revision>" in core
    assert "Priya Sharma" in core
    assert structural_failures(str(template), str(out)) == []
    assert not any("core.xml" in note for note in result.qa_notes), result.qa_notes


# ------------------------------------------------------------------ F4: PDFs

def _toolchain_pdf(path):
    from pypdf import PdfWriter
    from pypdf.generic import DecodedStreamObject, NameObject

    writer = PdfWriter()
    writer.add_blank_page(200, 200)
    writer.add_metadata({"/Producer": "LibreOffice 26.8.0.3 (AARCH64)", "/Creator": "Writer",
                         "/Author": "python-docx",
                         "/CreationDate": "D:20260919140218+05'30'"})
    xmp = DecodedStreamObject()
    xmp.set_data(b"<x:xmpmeta>LibreOffice Writer python-docx +05:30</x:xmpmeta>")
    xmp[NameObject("/Type")] = NameObject("/Metadata")
    writer._root_object[NameObject("/Metadata")] = writer._add_object(xmp)
    writer.write(str(path))


@pytest.mark.parametrize("with_source", [True, False])
def test_pdf_metadata_describes_the_document_not_the_converter(tmp_path, with_source):
    from pypdf import PdfReader

    from app.generation.pdf_renderer import scrub_pdf_metadata

    pdf = tmp_path / "out.pdf"
    _toolchain_pdf(pdf)
    source = None
    if with_source:
        document = base_docx.new_document()
        document.core_properties.title = "Offer of employment"
        document.core_properties.author = "Acme HR"
        source = tmp_path / "src.docx"
        document.save(str(source))
    scrub_pdf_metadata(pdf, source)

    raw = pdf.read_bytes()
    for word in (b"LibreOffice", b"Writer", b"python-docx", b"+05", b"xmpmeta"):
        assert word not in raw, word
    reader = PdfReader(str(pdf))
    assert "/Metadata" not in reader.trailer["/Root"]
    meta = dict(reader.metadata or {})
    if with_source:
        assert meta == {"/Title": "Offer of employment", "/Author": "Acme HR"}
    else:
        assert meta == {}
    assert not (tmp_path / "out.pdf.scrubbing").exists()


def test_an_unreadable_source_just_has_no_identity(tmp_path):
    from app.generation.pdf_renderer import _docx_identity

    bad = tmp_path / "bad.docx"
    bad.write_bytes(b"not a package")
    assert _docx_identity(bad) == {}


@pytest.mark.skipif(not __import__("app.generation.pdf_renderer",
                                   fromlist=["find_soffice"]).find_soffice(),
                    reason="LibreOffice is not installed")
def test_a_converted_pdf_names_no_toolchain(tmp_path):
    from pypdf import PdfReader

    from app.generation.legacy_assembly import assemble_from_html
    from app.generation.pdf_renderer import render_pdf

    source = tmp_path / "letter.docx"
    assemble_from_html("<h1>Offer</h1><p>Welcome aboard.</p>", str(source))
    result = render_pdf(source, tmp_path)
    raw = open(result.pdf_path, "rb").read()
    for word in (b"LibreOffice", b"Writer", b"python-docx", b"+05"):
        assert word not in raw, word
    reader = PdfReader(result.pdf_path)
    assert "/Metadata" not in reader.trailer["/Root"]
    assert "Welcome aboard." in reader.pages[0].extract_text()


def test_the_overlay_font_has_a_generic_resource_name():
    from app.generation.pdf_renderer import OVERLAY_FONT_NAME

    assert OVERLAY_FONT_NAME == "/F9"


# ------------------------------------------------------------ F6: the workbook

def test_the_data_template_names_the_organisation_not_the_library():
    from app.generation.source_template import build_workbook

    manifest = {"fields": [{"id": "salary", "label": "Salary", "type": "text",
                            "required": True}], "conditions": [], "blocks": []}
    for author, expected in (("Acme Pty Ltd", "Acme Pty Ltd"), ("", "Template")):
        parts = _parts(io.BytesIO(build_workbook(manifest, author=author)))
        blob = b"".join(parts.values())
        for word in (b"openpyxl", b"Openpyxl", b"DocuMind"):
            assert word not in blob, word
        assert b"<Application>" not in parts["docProps/app.xml"]
        core = parts["docProps/core.xml"].decode()
        if author:
            assert f">{author}</dc:creator>" in core
        comments = [v for k, v in parts.items() if k.startswith("xl/comments")]
        assert comments and expected.encode() in comments[0]
        assert b"salary" in b"".join(v for k, v in parts.items() if "sheet" in k) or \
            b"salary" in parts.get("xl/sharedStrings.xml", b"")


# ------------------------------------------------------------ F5: file names

def test_a_file_is_named_after_the_document():
    stamp = datetime(2026, 9, 19, 22, 30)
    doc_id = "3f9a1c2b-1111-4222-8333-444455556666"
    assert document_filename(document_type="Offer Letter", created_at=stamp,
                             document_id=doc_id, language="en", ext="docx") == \
        "Offer Letter - 2026-09-19 - 3f9a1c2b.docx"
    assert document_filename(document_type=None, created_at=stamp, document_id=doc_id,
                             language="English", ext="pdf") == \
        "Document - 2026-09-19 - 3f9a1c2b.pdf"
    assert document_filename(document_type="Offer/Letter", created_at=stamp,
                             document_id=doc_id, language="zh-CN", ext="docx") == \
        "Offer Letter - 2026-09-19 - 3f9a1c2b - zh-CN.docx"
    # A missing clock falls back to now, in UTC.
    assert re.match(r"Document - \d{4}-\d{2}-\d{2} - 00000000\.docx",
                    document_filename(document_type="", created_at=None, document_id="",
                                      language=None, ext=".docx"))


def test_names_are_safe_and_unique():
    assert safe_filename('CTD Module 3.2.A / 3.2.R: "x"?.docx') == \
        "CTD Module 3.2.A 3.2.R x.docx"
    assert safe_filename("...") == "Document"
    assert safe_filename("Module 3.2.P") == "Module 3.2.P"
    taken: set = set()
    assert [unique_name("a.docx", taken) for _ in range(3)] == \
        ["a.docx", "a (2).docx", "a (3).docx"]
    assert unique_name("README", {"README"}) == "README (2)"


def test_content_disposition_encodes_everything():
    header = content_disposition("Module 3.2.A / 3.2.R.docx")
    assert "/" not in header.split("filename*=")[1]
    assert header.startswith('attachment; filename="Module 3.2.A 3.2.R.docx"')
    wide = content_disposition("录用通知 - 2026-09-19 - 3f9a1c2b.pdf")
    assert 'filename="2026-09-19 - 3f9a1c2b.pdf"' in wide
    assert "%E5%BD%95" in wide
    assert 'filename="download.pdf"' in content_disposition("录用通知.pdf")


@pytest.fixture()
def two_documents(app_client, two_orgs):
    """Two approved documents in one project, with real files behind them."""
    from app.models import DocumentVersion, GeneratedDocument, Project, User
    from app.storage import abs_path
    from app.templates.emit_docx import emit

    token, project_id, *_ = two_orgs
    db = SessionLocal()
    try:
        project = db.get(Project, project_id)
        project.name = "Secret Workspace Name"
        user = db.scalar(select(User).where(User.org_id == project.org_id))
        ids = []
        for n in range(2):
            rel = f"generated/{project.id}/hygiene-{n}.docx"
            os.makedirs(str(abs_path(rel).parent), exist_ok=True)
            emit(_body(), str(abs_path(rel)))
            doc = GeneratedDocument(org_id=project.org_id, project_id=project.id,
                                    display_id=81000 + n, language="en")
            db.add(doc)
            db.flush()
            version = DocumentVersion(document_id=doc.id, org_id=doc.org_id, version_no=1,
                                      blob_path=rel, status="approved", created_by=user.id)
            db.add(version)
            db.flush()
            doc.current_version_id = version.id
            doc.status = "approved"
            ids.append((doc.id, version.id))
        db.commit()
        document_type = project.document_type
    finally:
        db.close()
    return token, ids, document_type


def test_a_download_is_named_after_the_document_not_the_workspace(app_client, two_documents):
    token, ids, document_type = two_documents
    doc_id, version_id = ids[0]
    got = app_client.get(f"/api/v1/document-versions/{version_id}/download",
                         headers=_auth(token))
    assert got.status_code == 200, got.text
    header = got.headers["content-disposition"]
    assert "Secret Workspace Name" not in header and "81000" not in header
    assert f"{doc_id[:8]}.docx" in header
    assert safe_filename(document_type) in header

    link = app_client.post(f"/api/v1/document-versions/{version_id}/download-url",
                           headers=_auth(token)).json()
    assert link["filename"].endswith(f"{doc_id[:8]}.docx")
    fetched = app_client.get(link["url"])
    assert fetched.status_code == 200, fetched.text
    assert f"{doc_id[:8]}.docx" in fetched.headers["content-disposition"]


def test_a_bulk_archive_has_neutral_headers_and_distinct_names(app_client, two_documents):
    token, ids, _type = two_documents
    first = ids[0][0]
    got = app_client.post("/api/v1/documents:download", headers=_auth(token),
                          json={"document_ids": [first, first, ids[1][0]]})
    assert got.status_code == 200, got.text
    with zipfile.ZipFile(io.BytesIO(got.content)) as archive:
        infos = archive.infolist()
        names = [i.filename for i in infos]
        assert len(set(names)) == len(names) == 3
        assert not any("Secret Workspace" in n for n in names)
        for info in infos:
            assert info.date_time == FIXED_ZIP_TIMESTAMP
            # A constant, never the source file's permissions.
            assert info.external_attr == 0o600 << 16 and info.create_system == 0


def test_fixed_zip_entries():
    info = fixed_zip_entry("a.txt")
    assert info.date_time == FIXED_ZIP_TIMESTAMP and info.external_attr == 0
