"""template manifests and clusters

Revision ID: 5d500fff2f2d
Revises: 39e343c0d30b
Create Date: 2026-07-24 12:11:27.474812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d500fff2f2d'
down_revision: Union[str, None] = '39e343c0d30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('representative_template_file_id', sa.String(), nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_manifests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('template_file_id', sa.String(), nullable=True),
    sa.Column('template_version_id', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('delete_always', sa.JSON(), nullable=False),
    sa.Column('protected_note', sa.Text(), nullable=False),
    sa.Column('compiled_by', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prescan_summary', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifest_generations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=False),
    sa.Column('source_record', sa.JSON(), nullable=False),
    sa.Column('field_lineage', sa.JSON(), nullable=False),
    sa.Column('condition_lineage', sa.JSON(), nullable=False),
    sa.Column('qa_passed', sa.Boolean(), nullable=False),
    sa.Column('qa_notes', sa.JSON(), nullable=False),
    sa.Column('blob_path', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['template_manifests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_cluster_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('template_file_id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('is_representative', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['template_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_cluster_members')
    op.drop_table('manifest_generations')
    op.drop_table('template_manifests')
    op.drop_table('template_clusters')
    # ### end Alembic commands ###
