"""field dictionary, manifest bindings, review tasks

Revision ID: 860cde4d3161
Revises: 5d500fff2f2d
Create Date: 2026-08-04 13:44:47.332214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860cde4d3161'
down_revision: Union[str, None] = '5d500fff2f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_dictionary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('locale_hints', sa.JSON(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_dictionary_canonical_id'), 'field_dictionary', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_field_dictionary_org_id'), 'field_dictionary', ['org_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('generation_id', sa.String(), nullable=True),
    sa.Column('manifest_id', sa.String(), nullable=True),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('proposed_value', sa.Text(), nullable=True),
    sa.Column('resolved_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_generation_id'), 'review_tasks', ['generation_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_org_id'), 'review_tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_project_id'), 'review_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('manifest_bindings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('manifest_id', sa.String(), nullable=False),
    sa.Column('source_version_id', sa.String(), nullable=False),
    sa.Column('field_bindings', sa.JSON(), nullable=False),
    sa.Column('value_map', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['template_manifests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_bindings_manifest_id'), 'manifest_bindings', ['manifest_id'], unique=False)
    op.create_index(op.f('ix_manifest_bindings_org_id'), 'manifest_bindings', ['org_id'], unique=False)
    op.create_index(op.f('ix_manifest_bindings_source_version_id'), 'manifest_bindings', ['source_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manifest_bindings_source_version_id'), table_name='manifest_bindings')
    op.drop_index(op.f('ix_manifest_bindings_org_id'), table_name='manifest_bindings')
    op.drop_index(op.f('ix_manifest_bindings_manifest_id'), table_name='manifest_bindings')
    op.drop_table('manifest_bindings')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_project_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_org_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_generation_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_field_dictionary_org_id'), table_name='field_dictionary')
    op.drop_index(op.f('ix_field_dictionary_canonical_id'), table_name='field_dictionary')
    op.drop_table('field_dictionary')
    # ### end Alembic commands ###
