"""The spreadsheet a template asks for, generated from its own manifest.

Binding exists because a customer's data was written before their template was
compiled: an HR export calls a column `DRV_Employment_Type` and holds
`Full Time`, and something has to work out that this is the template's
`work_schedule`. That inference is the hardest part of the product and it is
where it goes wrong -- measured on a real Pfizer transfer letter, the binder
matched `employment_type` to `DRV_Employment_Type` on the strength of the name,
which is where the values for `work_schedule` actually live. Two conditions then
tested the wrong column, one letter lost its work-schedule paragraph entirely,
and a part-time colleague was sent a letter describing full-time employment
that passed every QA gate on the way out.

This module removes the inference from the cases where it was never necessary.
Given a compiled manifest it emits the workbook that template binds to exactly:
one column per bindable target, headed by the field id itself, so the binder's
exact-slug path matches every target to the column of the same name.

That fixes the mapping, not the paperwork. Every suggestion still arrives in the
REVIEW band, because §13's auto-accept floor is 0.97 and only four of its seven
signals are computed -- the highest score this codebase can currently produce is
0.9181, for any mapping however obviously right. A reviewer still confirms the
list; what changes is that the list is correct before they look at it, and that
no condition value arrives with no branch to select.

Nothing here is generated by a model. The manifest already carries the fields,
their declared types, and -- through the condition expressions -- the exact
strings each branch tests for. Asking a model to restate that would reintroduce
the invention this pipeline spent its design budget removing; the compiler's
output is the schema, and this is a rendering of it.

The dropdowns are the point. A condition column offers exactly the values its
branches test, so `Ongoing` cannot be typed where the manifest says `Regular`.
That is not a nicety: it makes the failure above unreachable rather than caught
late by a canary batch, and a value that never enters the spreadsheet never
needs a `value_map` entry to rescue it.
"""

from __future__ import annotations

import io
import re
from dataclasses import dataclass

from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

from app.generation.docx_renderer import EQUALITY_CONDITION_RE
from app.generation.source_resolver import bindable_targets

#: The sheet the reader takes its records from. `extract_records` defaults to
#: `worksheets[0]`, so this must be created first; `DATA_SHEET` is also the name
#: the UI passes back as `sheet` once a workbook has more than one.
DATA_SHEET = "SourceData"
GUIDE_SHEET = "Field guide"

#: How many rows below the header get the column's formatting and validation.
#: A hard number rather than the whole column because Excel applies whole-column
#: validation to a million cells and some readers labour over it. Someone
#: generating more letters than this in one batch can paste past the boundary --
#: the reader does not care, only the dropdowns stop.
PREPARED_ROWS = 500

#: Excel refuses an inline validation list longer than this, and truncates
#: silently in some versions rather than erroring. A manifest whose branch
#: values exceed it loses its dropdown and gains a line in the field guide,
#: which is worse but honest -- a half-populated dropdown would be a lie about
#: what the template accepts.
MAX_INLINE_LIST = 250

_HEADER_FILL = PatternFill("solid", fgColor="1F3864")
_HEADER_FONT = Font(color="FFFFFF", bold=True)
_REQUIRED_FILL = PatternFill("solid", fgColor="C00000")


@dataclass(frozen=True)
class Column:
    """One column of the workbook, and everything the guide has to say about it."""

    field_id: str
    label: str
    declared_type: str
    required: bool
    permitted: tuple[str, ...]
    origin: str

    @property
    def is_condition(self) -> bool:
        return bool(self.permitted)


def _humanise(field_id: str) -> str:
    """`colleague_first_name` -> "Colleague first name"."""
    words = [w for w in re.split(r"[_\s]+", field_id) if w]
    if not words:
        return field_id
    return " ".join(words).capitalize()


def permitted_values(manifest: dict) -> dict[str, list[str]]:
    """For each condition variable, the exact strings its branches test for.

    Read from the expressions rather than from any separate declaration, for the
    same reason `plain_english` renders from the AST: a list maintained beside
    the rule drifts from it, and a dropdown offering a value no branch tests is
    an instruction to produce a document with a section missing.

    Only equality conditions contribute. `salary > 100000` constrains a column
    to no finite set, so it gets a free-text cell and a note in the guide.
    """
    offered: dict[str, list[str]] = {}
    for condition in manifest.get("conditions") or []:
        match = EQUALITY_CONDITION_RE.match(condition.get("expression") or "")
        if not match:
            continue
        name, value = match.group(1), match.group(2)
        values = offered.setdefault(name, [])
        if value not in values:
            values.append(value)
    return offered


def plan_columns(manifest: dict) -> list[Column]:
    """The columns this template needs, in the order a person should fill them.

    `bindable_targets` rather than `manifest["fields"]`: a condition variable
    that appears in no placeholder still has to arrive from somewhere, and a
    workbook built from the field list alone would omit exactly the columns
    whose absence deletes conditional sections silently.

    Condition columns lead. They decide which sections of the letter exist at
    all, so a person filling this in should answer them before typing prose into
    a paragraph that a later answer removes.
    """
    offered = permitted_values(manifest)
    columns = [
        Column(
            field_id=target.field_id,
            label=_humanise(target.field_id),
            declared_type=target.declared_type or target.type or "string",
            required=bool(target.required),
            permitted=tuple(offered.get(target.field_id, ())),
            origin=target.origin,
        )
        for target in bindable_targets(manifest)
    ]
    columns.sort(key=lambda c: (not c.is_condition, c.field_id))
    return columns


def _validation_for(column: Column) -> DataValidation | None:
    """A dropdown constrained to the branch values, or nothing.

    Returns None when a value contains a comma or a double quote. Excel's inline
    list is comma-separated with no escape, so such a value would split into two
    wrong options -- and a dropdown that silently offers the wrong strings is
    more dangerous than no dropdown, because it looks authoritative.
    """
    if not column.permitted:
        return None
    if any("," in v or '"' in v for v in column.permitted):
        return None
    joined = ",".join(column.permitted)
    if len(joined) > MAX_INLINE_LIST:
        return None
    validation = DataValidation(
        type="list",
        formula1=f'"{joined}"',
        allow_blank=True,
        showDropDown=False,  # openpyxl inverts this: False *shows* the arrow
    )
    validation.error = (
        "This column decides which sections of the letter are kept. "
        f"The template only tests for: {', '.join(column.permitted)}."
    )
    validation.errorTitle = "Not a value this template tests for"
    validation.prompt = f"Choose one of: {', '.join(column.permitted)}"
    validation.promptTitle = column.label
    return validation


def _header_note(column: Column) -> str:
    parts = [column.label]
    if column.is_condition:
        parts.append("Decides which sections are kept.")
        parts.append("Permitted: " + ", ".join(column.permitted))
    if column.required:
        parts.append("Required -- a blank here blocks the document.")
    if column.declared_type in ("date",):
        parts.append("Type the date exactly as it should read in the letter.")
    return "\n".join(parts)


def build_workbook(manifest: dict, *, template_name: str = "") -> bytes:
    """The .xlsx a person fills in for this template, as bytes.

    The data sheet is created first because `extract_records` reads
    `worksheets[0]` whenever no sheet is named, so a guide sheet in front of it
    would make the default read return documentation instead of records.
    """
    columns = plan_columns(manifest)

    workbook = Workbook()
    data = workbook.active
    data.title = DATA_SHEET

    for index, column in enumerate(columns, start=1):
        letter = get_column_letter(index)
        # The header is the field id, not the human label. It is what the binder
        # matches on, and an exact slug match is the one signal §13 scores at
        # full strength -- so every column pairs with its own field instead of
        # being guessed at by name similarity. A prettified header would put this
        # file back through the same fuzzy matching it exists to avoid.
        cell = data.cell(row=1, column=index, value=column.field_id)
        cell.font = _HEADER_FONT
        cell.fill = _REQUIRED_FILL if column.required else _HEADER_FILL
        cell.alignment = Alignment(vertical="center", wrap_text=False)
        cell.comment = Comment(_header_note(column), "DocuMind")
        data.column_dimensions[letter].width = max(14, min(38, len(column.field_id) + 4))

        validation = _validation_for(column)
        if validation is not None:
            data.add_data_validation(validation)
            validation.add(f"{letter}2:{letter}{PREPARED_ROWS + 1}")

        if column.declared_type == "date":
            # Text, deliberately. `source_ingestion._clean_cell` stringifies
            # whatever openpyxl hands back, so a real Excel date arrives as
            # "2024-07-01 00:00:00" and that is what would be printed in the
            # letter. Holding the column as text keeps "01 July 2024" the
            # literal string the person typed.
            for row in range(2, PREPARED_ROWS + 2):
                data.cell(row=row, column=index).number_format = "@"

    data.freeze_panes = "A2"

    guide = workbook.create_sheet(GUIDE_SHEET)
    guide.append(["Column", "Means", "Type", "Required", "Permitted values"])
    for cell in guide[1]:
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
    for column in columns:
        guide.append([
            column.field_id,
            column.label + (" — decides which sections are kept" if column.is_condition else ""),
            column.declared_type,
            "Yes" if column.required else "",
            ", ".join(column.permitted) if column.permitted else "",
        ])
    for index, width in enumerate((34, 52, 12, 10, 40), start=1):
        guide.column_dimensions[get_column_letter(index)].width = width
    guide.freeze_panes = "A2"

    notes = [
        "",
        f"Generated for: {template_name}" if template_name else "",
        "",
        "One row produces one document. Leave no blank rows between records.",
        "Do not rename the column headers -- they are what the template matches on.",
        "Do not add an example or legend row: every row is treated as a person.",
        "Columns shaded red are required; a blank in one blocks that document.",
    ]
    for line in notes:
        guide.append([line])

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def filename_for(template_name: str) -> str:
    """A filename that says which template the workbook belongs to."""
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", (template_name or "template").strip()) or "template"
    stem = re.sub(r"\.docx?$", "", stem, flags=re.IGNORECASE)
    return f"{stem[:80]}_source_template.xlsx"
