"""The neutral package every document built from scratch starts from.

`docx.Document()` with no argument opens python-docx's own default template,
and everything in that package travels to whoever receives the file: a core
properties part whose author is "python-docx" and whose description reads
"generated by python-docx", an extended-properties part claiming Microsoft
Macintosh Word 14 and `Normal.dotm`, a bibliography custom-XML part with a
fixed GUID, a thumbnail image, and the revision-session ids (`w:rsids`,
`w14:docId`) of whoever built that template in 2013. None of it is document
content and all of it describes how the document was produced.

`BASE_DOCX` is that same template with those parts removed and nothing else
changed. Styles, numbering, theme, fonts and document defaults are the default
template's bytes, so a document emitted from it lays out exactly as before and
every golden comparison of `word/` still holds.

The asset is checked in, and `build` regenerates it. A test rebuilds it and
compares bytes, so the file on disk can never drift from the recipe here.

    python -m app.templates.base_docx     # rewrite app/templates/assets/base.docx

Only for documents this product creates. A customer's template is never
rebuilt from this: the fill path edits the customer's own package, and the
static-region gate compares that package part for part with the template.
"""

from __future__ import annotations

import os
import re
import zipfile

import docx

#: The asset every from-scratch document opens.
BASE_DOCX = os.path.join(os.path.dirname(__file__), "assets", "base.docx")

#: Parts the default template carries that no document of ours should: a
#: bibliography store with a fixed GUID, and a picture of an empty page.
DROPPED_PARTS = (
    "customXml/_rels/item1.xml.rels",
    "customXml/item1.xml",
    "customXml/itemProps1.xml",
    "docProps/thumbnail.jpeg",
)

#: No author, no description, no application. The clocks are pinned by
#: `reproducibility.normalise_docx` on every save anyway; they are pinned here
#: too so the asset itself is reproducible.
CORE_XML = (
    "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>\n"
    '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/'
    'core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" '
    'xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n'
    "  <dc:title/>\n"
    "  <dc:creator/>\n"
    "  <cp:lastModifiedBy/>\n"
    "  <cp:revision>1</cp:revision>\n"
    '  <dcterms:created xsi:type="dcterms:W3CDTF">1980-01-01T00:00:00Z</dcterms:created>\n'
    '  <dcterms:modified xsi:type="dcterms:W3CDTF">1980-01-01T00:00:00Z</dcterms:modified>\n'
    "</cp:coreProperties>\n"
)

#: The extended properties with nothing that names a program or a template.
APP_XML = (
    "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>\n"
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/'
    'extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/'
    'docPropsVTypes">\n'
    "  <DocSecurity>0</DocSecurity>\n"
    "  <ScaleCrop>false</ScaleCrop>\n"
    "  <LinksUpToDate>false</LinksUpToDate>\n"
    "  <SharedDoc>false</SharedDoc>\n"
    "  <HyperlinksChanged>false</HyperlinksChanged>\n"
    "</Properties>\n"
)

#: Text edits, each of which must match exactly once. A python-docx upgrade
#: that reshapes its template fails the build loudly instead of shipping a
#: half-cleaned package.
_EDITS = {
    "[Content_Types].xml": (
        r'\s*<Default Extension="jpeg" ContentType="image/jpeg"/>',
        r'\s*<Override PartName="/customXml/itemProps1\.xml"[^>]*/>',
    ),
    "_rels/.rels": (
        r'\s*<Relationship Id="rId2" Type="[^"]*/metadata/thumbnail"[^>]*/>',
    ),
    "word/_rels/document.xml.rels": (
        r'\s*<Relationship Id="rId1" Type="[^"]*/customXml"[^>]*/>',
    ),
    "word/settings.xml": (
        r"\s*<w:savePreviewPicture/>",
        r"\s*<w:rsids>.*?</w:rsids>",
        r'\s*<w14:docId w14:val="[^"]*"/>',
    ),
}


class BaseTemplateChanged(RuntimeError):
    """python-docx's default template no longer has the shape this recipe
    removes things from."""


def _default_template() -> str:
    return os.path.join(os.path.dirname(docx.__file__), "templates", "default.docx")


def build(output_path: str = BASE_DOCX, source_path: str | None = None) -> str:
    """Write the neutral base package to `output_path` and return the path."""
    from app.generation.reproducibility import normalise_docx

    with zipfile.ZipFile(source_path or _default_template()) as source:
        parts = {info.filename: source.read(info.filename) for info in source.infolist()}

    for name in DROPPED_PARTS:
        if parts.pop(name, None) is None:
            raise BaseTemplateChanged(f"the default template has no {name} to remove")
    for name, patterns in _EDITS.items():
        text = parts[name].decode("utf-8")
        for pattern in patterns:
            text, count = re.subn(pattern, "", text, flags=re.DOTALL)
            if count != 1:
                raise BaseTemplateChanged(
                    f"{name}: expected one match for {pattern!r}, found {count}")
        parts[name] = text.encode("utf-8")
    parts["docProps/core.xml"] = CORE_XML.encode("utf-8")
    parts["docProps/app.xml"] = APP_XML.encode("utf-8")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as out:
        for name, data in parts.items():
            out.writestr(name, data)
    return normalise_docx(output_path)


def new_document():
    """A blank python-docx document on the neutral package."""
    return docx.Document(BASE_DOCX)


if __name__ == "__main__":  # pragma: no cover - the regeneration entry point
    print(build())
