/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppQualityRouteImport } from './routes/_app.quality'
import { Route as AppGuideRouteImport } from './routes/_app.guide'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAuditLogRouteImport } from './routes/_app.audit-log'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppTemplatesBlueprintIdRouteImport } from './routes/_app.templates_.$blueprintId'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppProjectsIdEditDocIdRouteImport } from './routes/_app.projects.$id_.edit.$docId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesBlueprintIdRoute = AppTemplatesBlueprintIdRouteImport.update({
  id: '/templates_/$blueprintId',
  path: '/templates/$blueprintId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdEditDocIdRoute = AppProjectsIdEditDocIdRouteImport.update({
  id: '/projects/$id_/edit/$docId',
  path: '/projects/$id/edit/$docId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-log': typeof AppAuditLogRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/guide': typeof AppGuideRoute
  '/quality': typeof AppQualityRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/templates/$blueprintId': typeof AppTemplatesBlueprintIdRoute
  '/projects/$id/edit/$docId': typeof AppProjectsIdEditDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-log': typeof AppAuditLogRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/guide': typeof AppGuideRoute
  '/quality': typeof AppQualityRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/templates/$blueprintId': typeof AppTemplatesBlueprintIdRoute
  '/projects/$id/edit/$docId': typeof AppProjectsIdEditDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/guide': typeof AppGuideRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/templates_/$blueprintId': typeof AppTemplatesBlueprintIdRoute
  '/_app/projects/$id_/edit/$docId': typeof AppProjectsIdEditDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/analytics'
    | '/audit-log'
    | '/chat'
    | '/dashboard'
    | '/guide'
    | '/quality'
    | '/review'
    | '/settings'
    | '/team'
    | '/templates'
    | '/projects/$id'
    | '/templates/$blueprintId'
    | '/projects/$id/edit/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/analytics'
    | '/audit-log'
    | '/chat'
    | '/dashboard'
    | '/guide'
    | '/quality'
    | '/review'
    | '/settings'
    | '/team'
    | '/templates'
    | '/projects/$id'
    | '/templates/$blueprintId'
    | '/projects/$id/edit/$docId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/docs'
    | '/login'
    | '/_app/analytics'
    | '/_app/audit-log'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/guide'
    | '/_app/quality'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/templates'
    | '/_app/projects/$id'
    | '/_app/templates_/$blueprintId'
    | '/_app/projects/$id_/edit/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide': {
      id: '/_app/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates_/$blueprintId': {
      id: '/_app/templates_/$blueprintId'
      path: '/templates/$blueprintId'
      fullPath: '/templates/$blueprintId'
      preLoaderRoute: typeof AppTemplatesBlueprintIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/edit/$docId': {
      id: '/_app/projects/$id_/edit/$docId'
      path: '/projects/$id/edit/$docId'
      fullPath: '/projects/$id/edit/$docId'
      preLoaderRoute: typeof AppProjectsIdEditDocIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuideRoute: typeof AppGuideRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppTemplatesBlueprintIdRoute: typeof AppTemplatesBlueprintIdRoute
  AppProjectsIdEditDocIdRoute: typeof AppProjectsIdEditDocIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuideRoute: AppGuideRoute,
  AppQualityRoute: AppQualityRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppTemplatesBlueprintIdRoute: AppTemplatesBlueprintIdRoute,
  AppProjectsIdEditDocIdRoute: AppProjectsIdEditDocIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
